# Generated by Django 4.0.6 on 2022-07-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_date',), 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ('-created_date',), 'verbose_name': 'Информация о приобритаемом товаре', 'verbose_name_plural': 'Информации о приобритаемых товарах'},
        ),
        migrations.AlterModelOptions(
            name='tradepartner',
            options={'ordering': ('-created_date',), 'verbose_name': 'Торговая организация', 'verbose_name_plural': 'Торговые организации'},
        ),
    ]
