# Generated by Django 4.0.6 on 2022-07-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_date',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientsalary',
            options={'ordering': ('-created_date',), 'verbose_name': 'Доход клиента', 'verbose_name_plural': 'Доходы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='clientspend',
            options={'ordering': ('-created_date',), 'verbose_name': 'Расход клиента', 'verbose_name_plural': 'Расходы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='dependent',
            options={'ordering': ('-created_date',), 'verbose_name': 'Иждевенец', 'verbose_name_plural': 'Иждевенцы'},
        ),
        migrations.AlterModelOptions(
            name='guarantor',
            options={'ordering': ('-created_date',), 'verbose_name': 'Поручитель', 'verbose_name_plural': 'Поручители'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_date',), 'verbose_name': 'Работу клиента', 'verbose_name_plural': 'Работы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ('-created_date',), 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='spouse',
            options={'ordering': ('-created_date',), 'verbose_name': 'Супруг/а', 'verbose_name_plural': 'Супруги'},
        ),
    ]
