# Generated by Django 4.0.6 on 2022-08-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcommercial',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес организации'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование орг.'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='№ИНН/патента/свидетельство'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='organization_information',
            field=models.CharField(blank=True, max_length=255, verbose_name='Деятельность организации'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='сом/мес', max_digits=8, verbose_name='Доходы(чистая прибыль)'),
        ),
        migrations.AlterField(
            model_name='clientcommercial',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата начала деятельности'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent', to='client.client', verbose_name='Клиент'),
        ),
    ]
