# Generated by Django 4.0.6 on 2022-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientcommercial_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес организации'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_definition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Деятельность компании'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_of_employment',
            field=models.DateField(blank=True, verbose_name='Дата принятия на работу'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
    ]
