# Generated by Django 4.0.6 on 2022-07-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_guarantor_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='client',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarantor', to='client.client', verbose_name='Клиент'),
        ),
    ]
