# Generated by Django 4.0.6 on 2022-07-20 11:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandocument',
            options={'ordering': ('-created_date',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='loanproduct',
            options={'ordering': ('-created_date',), 'verbose_name': 'Кредитный продукт', 'verbose_name_plural': 'Кредитные продукты'},
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='loanconsultation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_consultation', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 12, 0), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='% ставка'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
    ]
