# Generated by Django 4.0.6 on 2022-08-04 18:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_system', '0003_loaninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст информации'),
        ),
    ]
