# Generated by Django 4.0.6 on 2022-08-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0002_alter_address_options_alter_city_options_and_more'),
        ('loan_system', '0004_alter_loaninfo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlimitamount',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_limit', to='company_structure.position', verbose_name='Должность'),
        ),
    ]
