# Generated by Django 4.0.6 on 2022-08-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0002_alter_address_options_alter_city_options_and_more'),
        ('loan_system', '0005_alter_loanlimitamount_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlimitamounthistory',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='company_structure.position', verbose_name='Должность'),
        ),
    ]
