# Generated by Django 4.0.6 on 2022-08-06 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_system', '0006_alter_loanlimitamounthistory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начисленные проценты'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.CharField(default='test', max_length=150, verbose_name='Залоговое обеспечение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_cost',
            field=models.CharField(default=0, max_length=150, verbose_name='Стоимость залогового обеспечения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дисконт'),
        ),
        migrations.AddField(
            model_name='loan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Дисконт %'),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_restructuring',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Кредит реструктуризирован'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.CharField(default='test', max_length=50, verbose_name='Назначение кредита'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='restructuring_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во реструктуризаций'),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructuring_date',
            field=models.DateTimeField(default='2022-01-02', verbose_name='Дата реструктуризации кредита'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='rppu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='РППУ'),
        ),
        migrations.AddField(
            model_name='loan',
            name='rppu_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='РППУ %'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='overdue_principal_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Просроченный основной долг'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='urgent_principal_debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Срочный основной долг'),
        ),
    ]
