# Generated by Django 4.0.6 on 2022-08-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ('-created_date',), 'verbose_name': 'Бонус', 'verbose_name_plural': 'Бонусы'},
        ),
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ('-created_date',), 'verbose_name': 'История бонуса', 'verbose_name_plural': 'История бонусов'},
        ),
        migrations.AlterModelOptions(
            name='disciplinaryaction',
            options={'ordering': ('-created_date',), 'verbose_name': 'Дисциплинарное взыскание', 'verbose_name_plural': 'Дисциплинарные взыскания'},
        ),
        migrations.AlterModelOptions(
            name='disciplinaryactionhistory',
            options={'ordering': ('-created_date',), 'verbose_name': 'История дисциплинарного взыскания', 'verbose_name_plural': 'История дисциплинарных взысканий'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-created_date',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='positionhistory',
            options={'ordering': ('-created_date',), 'verbose_name': 'Хронология должности сотрудника', 'verbose_name_plural': 'Хронология должностей сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ('-created_date',), 'verbose_name': 'Зарплата', 'verbose_name_plural': 'Зарплаты'},
        ),
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'ordering': ('-created_date',), 'verbose_name': 'История зарплаты', 'verbose_name_plural': 'История зарплат'},
        ),
    ]
