# Generated by Django 4.0.6 on 2022-07-19 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_balance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_balance.account', verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='balance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_structure.officebranch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='balance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
