# Generated by Django 4.0.6 on 2022-08-04 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_system', '0001_initial'),
        ('trade_partner', '0001_initial'),
        ('company_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма перевода')),
                ('is_transfered', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Средства переведены ТО')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_branch_transfers', to='company_structure.officebranch', verbose_name='Филиал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_employee_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='money_transfer', to='loan_system.loan', verbose_name='Кредит')),
                ('trade_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_money_transfers', to='trade_partner.tradepartner', verbose_name='Торговая организация')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ('-created_date',),
            },
        ),
    ]
