# Generated by Django 4.0.6 on 2022-08-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_date',), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адресы'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-created_date',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-created_date',), 'verbose_name': 'Департамент/Отдел', 'verbose_name_plural': 'Департаменты/Отделы'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('-created_date',), 'verbose_name': 'Праздник', 'verbose_name_plural': 'Праздники'},
        ),
        migrations.AlterModelOptions(
            name='officebranch',
            options={'ordering': ('-created_date',), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('-created_date',), 'verbose_name': 'Регион/Район', 'verbose_name_plural': 'Регионы/Районы'},
        ),
        migrations.AddField(
            model_name='department',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01', verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время открытия филиала')),
                ('end_time', models.TimeField(verbose_name='Время закрытия филиала')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company_structure.officebranch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Время работы филиала',
                'verbose_name_plural': 'Время работы филиалов',
                'ordering': ('-created_date',),
            },
        ),
    ]
